<?php

$maximes = [

/* La lumière du papillon */

"Rêve de tout, mais cours vers l'essentiel, il est plus que suffisant.", 
"Tu manques de confiance ? Suis ton intuition ...",
"Une âme joyeuse n'a pas d'âge, alors joue!",
"Chaque jour est un jour de chance: crois-le fort, aie confiance.",
"Ton monde est sombre ? Choisis tes couleurs !",
"Tu cherches le bonheur ? Il est à portée de ton cœur.",
"Ne rêve pas de l'amour; vis-le avec tout le bonheur du monde.",
"Tu te sens prisonnier, mais prisonnier de quoi ? Regarde, la porte est ouverte !",
"Si ton cœur semble mort, bats-toi pour les rêves qui sommeillent en toi",
"Fais ce que tu aimes sans nuire à autrui, ta joie n'en sera que plus grande.",
"Considère-toi comme une étoile la nuit et sois magnifique comme la rosée du matin.",
"la vie est une course que tu ne feras qu'une seule fois; cours pour gagner.",
"Tu as plein d'idées, manifeste-les.",
"Quitte la mélancolie, ose la vie !",
"Lance-toi, ce que tu souhaites va arriver.",
"Laisse couler l'amour dans ta vie: il te remplira de joie et le bonheur jaillira.",
"Cherches en toi la rose blanche, le diamant pur, l'éclat de Dieu.",
"La joie arrive quand tu te construis",
"Ta vie est sombre ? Cherche en toi l'interrupteur !",
"Sois certain(e) que la liberté est déjà en toi.",
"Fais jaillir l'étincelle qui est en toi: tout sera lumière",
"Tout commence quand tu décides d'avancer, enlève le frein à main et roule",
"La vie est un cadeau: accepte-le, saisis chaque instant et sois généreux(se)",
"L'amour est dans l'air, n'arrêtes pas de respirer",
"Avec le temps, tu pourras expérimenter l'amour et tu diras merci",
"Ne cherche pas l'amour. Prie, ton cœur saura le trouver.",
"Prends le temps d'aimer sans peur, la lumière jaillira.",
"Le tableau de ta vie ne te plais pas ? A tes pinceaux, choisis tes couleurs !",
"Vis tes rêves: l'impossible est à portée.",
"Si ton monde est laid, sois positif(ve):sa beauté se révèlera.",
"Ta vie est triste ? Cultive la lumière au fond de ton être.",
"Cherche avec ton cœeur, tu trouveras.",
"Sois attentif(ve) à la joie: elle embellit les états d'âme.",
"Donne sans égoïsme, la vie te le rendra.",
"Sois vrai(e) avec toi-même et brille de tous tes feux.",
"Rends grâce à l'amour, l'exaucement ne saurait tarder",
"Réfléchis dans le secret de ton cœur. Fais silence et tu verras plus clair",
"Il n'est jamais trop tard pour retrouver ses rêves, ses yeux et son cœur d'enfant.",
"Illumine ta vie, suis ta destinée. Au fond de toi, tu es capable de trouver le chemin",
"Ressentir l'amour est une chance que tous les cœurs sombres envient.",
"N'achète pas le bonheur, il n'a pas de prix; cherche sa juste valeur.",
"Cultive de belles paroles, sois ébloui(e) des vérités.",
"Ose ta vie: elle commencera quand tu laisseras place au positif.",
"Corrige-toi sans violence, cherche la paix.",
"La vie est une école,retiens ses leçons.",
"Aie une soif insatiable de paix, sois affamé(e), de vérité et comblé(e) d'amour.",
"Ta force est à l'intérieur. Puise en toi.",
"Le bonheur frappe à toutes les portes, émerveille-toi tous les jours",
"Ne lâche pas tes rêves, laisse-toi surprendre par la récompense.",
"Avance avec la lumière et laisse lombre qui t'encombre derrière toi.",
"Pourquoi penser qu'il ne t'est plus permis de rêver ? Tes frontières t'appartiennent.",
"Honore ta vie, ne la gaspille pas, elle est précieuse.",
"Sois optimiste en toutes circonstances, l'avenir fera le reste.",
"Seuls les cœurs sincères et humbles peuvent sentir le parfum de l'amour.",
"Remercie ton endurance et ta persévérance le jour de la réuissite.",
"Une vie dans le mensonge est sous lumière artificielle.",
"Ton cœeur est froid ? Ranime le feu divin qui couve en toi.",
"Quand les portes s'ouvrent, aie l'audace de les franchir... Le meilleur t'attend",
"Donne ta vie sans inquiétude, tu en ressortiras grandi(e).",
"La flamme d'un cœur sincère et respectueux est le plus beau des feux.",
"Prends conscience de l'abondance, jamais du manque.",
"Profite de l'instant présent, prends conscience de ton bonheur.",
"Tes qualités et tes défauts font de toi un être unique.",
"Réfugie-toi un moment dans le silence pour donner du repos à ton esprit.",
"Ne laisse pas l'angoisse te submerger. Prends fermement possession de ta vie.",
"Vis à la même fréquence que ton cœur, il bat au rythme de l'amour inconditionnel.",
"Accepte-toi vértitablement. Aime-toi avant toute chose.",
"Ouvre-toi au bonheur pour contempler l'aurore.",
"Trouve chaque jour un moyen d'aider les autres.",
"Arrête de te mentir, sois vrai(e) avec toi-même",
"L'amour devrait toujours vibrer positivement. Ne pleure que de joie.",
"Apprécie les autres, tu connaîtras le vrai bonheur du partage.",
"Un bateau bien ancré ne s'égare pas dans l'orage.",
"Prends le temps d'apprécier le chemin parcouru.",
"Garde ton esprit ouvert pour entendre les belles idées venir à toi.",
"Fais face à l'épreuve et conserve une attitude positive.",
"Tu es précieux(se) pour quelqu'un.",
"Pense avec bienveillance et reçois avec joie l'amour en reconnaissance.",
"Le don de soi est une valeur sûre. Il apporte toujours le meilleur.",
"Tourne la page du passé, tu as un fabuleux potentiel à exploiter.",
"Courage ! Elance-toi, une réalité pleine de promesses t'attend.",
"Apprécie la beauté de la simplicité. Simplifie ta vie.",
"L'amour est parfait quand il est sincère.",
"Un esprit bon est toujours dans l'espérance.",
"Respire! Inspire l'énergie de l'amour, expire les ondes négatives.",
"Ne sous-estime pas ton courage, ta force est en dedans.",
"Quand tout te semble sans issue, ouvre ton cœur davantage: l'espoir te donnera la clé.",
"Exprime à tes relations l'estime que tu leur portes.",
"Aie de la compassion pour autrui, exerce-toi à ne pas juger.",
"Prends la vie comme un cadeau, saisis chaque instant.",
"Demande pardon si tu te sens coupable.",
"Que ton reflet dans le miroir soit toujours celui d'un visage sincère et honnête.",
"Eclaire ce qui est essentiel sur le cheminement de l'amour.",
"Trouve des trésors dans le fait de posséder peu",
"Peu importe la longueur de ta nuit, le soleil finira par se lever",
"Dieu te réserve un grand destin; évite les raccourcis",
"La vérité résonne dans l'âme.",
"Les mots d'amour réconfortent le cœur, cherche-les à l'intérieur.",
"Appelle la lumière pour ne pas t'égarer sur la route de ta vie.",
"Ne laisse pas les autres te rendre amère, garde ton cœur plein d'amour et de bienveillance pour autrui.",
"Médite sur ton être. Tu sauras que ton cœur est un atout.",
"Ferme les yeux, plonge au plus profond de toi, tu trouveras l'amour inconditionnel.",
"Laisse-toi guider tout simplement. Ne t'inquiète de rien si ton cœur est en paix.",
"Ne t'enferme pas dans le passé, vois plus grand. L'univers est à l'œuvre dans ta vie.",
"S'accomplir dans la vie, c'est croire en l'amour inconditionnel et se laisser transformer.",
"Pardonne à tes amours passées et sois patient(e): l'amour véritable est proche.",
"Savoir lire dans une âme est le don d'un cœur sincère.",
"Aime l'autre même s'il est est loin. Les petits papillons sont là pour franchir les frontières.",
"Que ton soleil brille pour toi et que ses rayons illuminent le plus grand nombre.",
"La lumière te montre la direction, mais ne te laisse pas aveugler par la convoitise.",
"Que ta vie soit solide comme le roc et ton cœur tendre comme du coton.",
"Arme-toi de patience et de persévérence, tu verras s'accomplir des miracles.",
"Ta recherche d'amour te semble sans fin ? Laisse la brise légère du destin faire son chemin.",
"Sois rempli(e) d'amour et de lumière pour aider les autres.",
"Ne perds pas espoir même si le pas suivant n'est pas facile. Ne crains pas l'avenir.",
"La vie est devant toi, marche !",
"Ne t'endors pas, au risque de manquer le but",
"L'amour pardonne même dans l'épreuve. Quand tu es blessé(e), continue d'espérer.",
"Apprécie les mots positifs, ils ont un grand pouvoir sur ton présent et ton avenir.",
"Expérimente le bonheur en écoutant le chant d'un oiseau.",
"Si tu apprends à reconnaître le bonheur, tu connaîtras la joie.",
"La joie de l'amour inconditionnel te donnera la paix.",
"Sache à qui tu donnes ton cœur: la trahison est un poison.",
"Inspire-toi de la parole de Dieu pour écrire l'histoire de ta vie.",
"L'arnaque de ce monde te rend aveugle ? Ouvre les yeux !",
"Laisse-toi éblouir par les rayons de soleil.",
"Laisse ton cœur s'émerveiller d'un arc-en-ciel",
"Un amour qui se concrétise est une grâce, une union bénie de lumière.",
"L'amour mène à la compassion.",
"Hume le parfum de l'amour sincère; laisse la liqueur de ton cœeur t'enivrer.",
"Sème l'amour, cultive la lumière, tu récolteras la paix, le plus beau des trésors.",
"Ressens la joie et sois rempli(e) d'amour dès le matin.",
"Reste fort(e) en toute circonstance. Tu es déjà victorieux.",
"Aie soif de l'éternité. Chaque éclat d'étoile est un souffle de vie, un renouvellement.",
"Laisse le feu brûler en toi, mais ne le laisse pas te consumer.",
"Ton destin est sûr, continue d'y croire. Ne doute pas de tes capacités.",
"Comme la fleur s'ouvre pour accueillir le soleil, ton cœur s'ouvre pour accueillir l'amour.",
"L'amour façonne les cœurs blessés. Aime toujours plus.",
"Fonde ta vie sur la vérité, tu seras rempli(e) de joie.",
"La foi libère tes forces au service de tous. Donne le meilleur de toi-même.",
"Trouver l'âme sœur, c'est trouver son équilibre: l'amour fusionne en un seul cœur.",
"Cherche à déguster le fruit de l'amour. Ne te laisse pas gagner par l'amertume.",
"Vois plus loin que les difficultés, tu les surmonteras avec joie.",
"Brille comme une perle, sois précieux(se) comme le cœur.",
"Rêve tout éveillé(e), crois en toi.",
"Laisse le vent te porter et le souffle de vie se poser sur ton coeur.",
"Mets ton potentiel au service de l'amour et de la vérité.",
"Atteins la libération de ton âme en veillant sur ton cœur.",
"Puise en toi, déploie tes forces et sers le bien.",
"Un ciel obscurci emprisonne notre cœur. Cherche la sérénité et la lumière émergera.",
"La vie est ton héritage. Vis avec ardeur et sans douter, la richesse coulera à flots.",
"Apprécie ta valeur, accepte l'autre et savoure des moments de tranquillité.",
"Goûte au fruit de l'amour véritable. Lâche prise, ne force rien, tu y as droit depuis ta naissance.",
"Repose-toi et remets ta vie dans la droiture.",
"Prends du temps pour toi. Goûte au vrai plaisir pour donner du repos à ton âme.",
"Seul l'amour inconditionnel a le pouvoir de rallumer le feu là où il y a des cendres.",
"Sème la paix cultive la lumière et récolte l'amour.",
"Il n'y a pas de destinée sans les autres! Alors merci d'exister.",
"Les larmes sont un baume pour notre cœur souffrant, l'occasion d'arroser un nouveau jardin...",
"Laisse la paix prendre racine en toi et cueille le fruit de la joie",
"Espère le meilleur pour ta vie, elle te prépare des surprises.",
"Crée ta réalité. Reste juste et positif(ve) pour construire ton avenir.",

/*Libère ton inspiration */

"Un nouveau jour pour un nouveau chemin...",
"Voir le meilleur en chaque situation est la plus belle façon d'aborder l'existence.",
"Apprends à poser un regard différent sur le monde: tu pourras alors accueillir quelque chose de plus grand...",
"Les épreuves révèlent le fond de ton cœur.",
"Tu n'as aucun contrôle sur la direction du vent, mais tu peux régler les voiles pour arriver à bon port...",
"Ta nouvelle vie se crée dans un éclair d'inspiration...",
"La vie est la voie du milieu, la somme de deux forces qui s'équilibrent.",
"L'espoir et le courage sont essentiels pour se réaliser.",
"La passion est la flamme qui rend puissant.",
"Donner sa vie à l'autre par amour, c'est être certain de gagner le bonheur sans rien y perdre.",
"L'intention que tu mets dans chaque chose crée une dynamique qui donne une puissance nouvelle à ta vie!",
"Voir le meilleur en chaque situation est la plus belle façon d'aborder l'existence.",
"Reste reliée à ta nature profonde pour pleinement exprimer ton potentiel!",
"Pose un regard différent sur le monde: tu pourras alors accueillir quelque chose de plus grand...",
"Libère-toi des chaines de ton intellect pour plonger dans ton cœeur!",
"Dans la vie, tout est une histoire de détermination: la force est dans la vision...",
"A vivre d'illusions, on n'aperçoit que des mirages...",
"Seul l'amour te donne véritablement le pouvoir de rayonner comme le soleil...",
"Fais preuve d'audace, mais n'oublie pas que la vie est fragile...",
"L'amour donne à la vie un éclairage différent... Ne te contente pas d'en parler, manifeste-le!",
"Quiconque aspire à la grandeur doit apprendre l'humilité.",
"Suis tes rêves: ils connaissent la destination!",
"L'échec est un contretemps, pas une défaite.",
"Prends conscience de ton rayonnement...",
"C'est dans chaque larme que la tristesse s'en va...",
"Chaque obstacle est une incitation au courage",
"Une bonne action faite avec amour te fait grandir.",
"Pouvoir vivre pleinement en paix est une chance sans mesure...",
"Les excuses ne cacheraient-elles pas un manque d'engagement ?",
"Ton inconscient te souffle ses conseils... Ecoute-le!",
"Quand ton cœur est en larmes, c'est mon cœur qui pleure...",
"La fleur s'ouvre pour accueillir le soleil. Le cœur s'ouvre pour accueillir l'amour.",
"Les épreuves révèlent le fond de notre cœur.",
"Quand la vie est trop calme, on ne la ressent pas.",
"Le pardon est la plus grande forme d'amour...",
"Si tu n'as que les échecs de ta vie à écrire, persévère: tu finiras par écrire REUSSITE en lettres capitales!",
"Perdre fait partie du jeu pour réussir!",
"Applique ton cœur à connaitre la sagesse...",
"Quand tu cherches l'amour, efface tes frontières, traverse ton désert. Découvre qui tu es en chemin, persévère pour offrir le meilleur et laisse-toi surprendre!",
"Une critique franche vaut mieux qu'une amitié qui ne s'exprime pas...",
"Sans amour, tout est vanité et poursuite du vent...",
"L'or et l'argent peuvent faire briller les yeux, mais seule la splendeur du cœur peut combler...",
"Quand tu pleures, regarde le ciel: tu finiras par voir l'arc-en-ciel qui t'annonce le soleil!",
"L'intuition de ton cœur vient des profondeurs de ton innocence...",
"Qui est l'étoile qui fait battre ton ciel, celle dont les éclats illuminent ta vie ?",
"La vie récompense les audacieux: ne laisse pas la peur te paralyser!",
"Ne t'attarde pas sur le nœud qui t'empêche d'avancer: il peut cacher un cadeau surprenant!",
"Libère-toi du mépris: il rend captif et t'empêche de poursuivre ta vie...",
"Chaque blessure réduit la capacité à aimer: face à l'offense, décide de pardonner!",
"Sois volontaire, avance en appréciant la personne que tu es.",

];

?>